"""Core implementation package for pymetaheuristic."""

from . import (
    actions,
    api,
    callbacks,
    controllers,
    cooperation,
    engines,
    examples,
    execution,
    graphs,
    io,
    orchestration,
    reference,
    schemas,
    telemetry,
    termination,
    test_functions,
    tuner,
    utils,
    viz,
)

from .api import create_optimizer, get_algorithm_info, list_algorithms, optimize
from .callbacks import Callback, CallbackList, EarlyStopping, HistoryRecorder, ProgressPrinter
from .cooperation import cooperative_optimize, replay_cooperative_result
from .io import (
    load_checkpoint,
    load_result,
    result_from_json,
    result_to_json,
    save_checkpoint,
    save_result,
)
from .orchestration import orchestrated_optimize
from .reference import (
    ARGUMENT_REFERENCE,
    search_reference,
    print_reference,
    print_root_exports,
)
from .schemas import (
    ActionOutcome,
    ActionSpec,
    AgentSnapshot,
    CollaborativeConfig,
    DecisionPlan,
    OrchestratedCooperativeResult,
    OrchestrationSpec,
    OrchestratorSnapshot,
    RulesConfig,
)
from .telemetry import (
    convergence_data,
    export_history_csv,
    export_island_telemetry_csv,
    export_population_snapshots_json,
    export_replay_manifest_json,
    summarize_cooperative_result,
    summarize_result,
)
from .termination import Termination
from .test_functions import (
    FUNCTIONS,
    TEST_FUNCTIONS,
    ENGINEERING_BENCHMARKS,
    get_test_function,
    get_test_function_info,
    list_test_functions,
    get_engineering_benchmark,
    list_engineering_benchmarks,
    validate_known_optima,
    validate_engineering_benchmarks,
    get_cec2022_optimum,
    validate_cec2022_optima,
)
from .actions import estimate_action_cost
from .tuner import BenchmarkRunner, HyperparameterTuner
from .utils import (
    AVAILABLE_CHAOTIC_MAPS,
    AVAILABLE_INIT_STRATEGIES,
    AVAILABLE_REPAIR_STRATEGIES,
    AVAILABLE_TRANSFER_FUNCTIONS,
    AckleyProblem,
    BinaryAdapter,
    BinaryVar,
    CategoricalVar,
    ChaoticMap,
    FloatVar,
    FunctionalProblem,
    ConstrainedFunctionalProblem,
    IntegerVar,
    PermutationVar,
    Problem,
    RastriginProblem,
    RosenbrockProblem,
    SphereProblem,
    ZakharovProblem,
    apply_transfer,
    binarize,
    build_problem_spec,
    chaotic_init_function,
    chaotic_population,
    chaotic_sequence,
    decode_position,
    encode_position,
    full_array,
    get_init_function,
    get_repair_function,
    get_test_problem,
    list_test_problems,
    list_engineering_problems,
    get_engineering_problem,
    get_engineering_problem_spec,
    lhs_population,
    levy_flight,
    limit,
    limit_inverse,
    obl_population,
    rand,
    reflect,
    sobol_population,
    sstf_01, sstf_02, sstf_03, sstf_04,
    uniform_population,
    vstf_01, vstf_02, vstf_03, vstf_04,
    wang,
)
from .viz import (
    plot_diversity_chart,
    plot_diversity_comparison,
    plot_explore_exploit_chart,
    plot_global_best_chart,
    plot_run_dashboard,
    plot_runtime_chart,
)
from .graphs import (
    compare_convergence,
    plot_benchmark_summary,
    plot_benchmark_barplots,
    plot_benchmark_boxplots,
    plot_benchmark_rank_heatmap,
    plot_benchmark_runtime,
    plot_benchmark_convergence,
    plot_collaboration_network,
    plot_convergence,
    plot_function,
    plot_function_1d,
    plot_function_2d,
    plot_function_3d,
    plot_function_contour,
    plot_function_nd,
    plot_function_surface,
    plot_island_dynamics,
    plot_population_snapshot,
)

__all__ = [
    "FUNCTIONS",
    "TEST_FUNCTIONS",
    "ENGINEERING_BENCHMARKS",
    "list_test_functions",
    "get_test_function_info",
    "get_engineering_benchmark",
    "list_engineering_benchmarks",
    "validate_known_optima",
    "validate_engineering_benchmarks",
    "get_cec2022_optimum",
    "validate_cec2022_optima",
    "ActionOutcome", "ActionSpec", "AgentSnapshot",
    "ARGUMENT_REFERENCE",
    "Callback", "CallbackList", "EarlyStopping", "HistoryRecorder", "ProgressPrinter", "callbacks",
    "CollaborativeConfig", "DecisionPlan",
    "OrchestratedCooperativeResult", "OrchestrationSpec",
    "OrchestratorSnapshot", "RulesConfig",
    "actions", "api", "controllers", "cooperation",
    "cooperative_optimize", "convergence_data", "create_optimizer",
    "engines", "estimate_action_cost", "examples", "execution",
    "export_history_csv", "export_island_telemetry_csv",
    "export_population_snapshots_json", "export_replay_manifest_json",
    "get_algorithm_info", "get_test_function", "get_test_problem",
    "graphs", "list_algorithms", "optimize", "orchestration",
    "orchestrated_optimize", "print_reference", "print_root_exports",
    "reference", "replay_cooperative_result",
    "schemas", "search_reference",
    "summarize_cooperative_result", "summarize_result",
    "telemetry", "test_functions",
    "Termination", "termination",
    "plot_diversity_chart", "plot_diversity_comparison",
    "plot_explore_exploit_chart", "plot_global_best_chart",
    "plot_run_dashboard", "plot_runtime_chart", "viz",
    "compare_convergence", "plot_benchmark_summary",
    "plot_benchmark_barplots", "plot_benchmark_boxplots",
    "plot_benchmark_rank_heatmap", "plot_benchmark_runtime",
    "plot_benchmark_convergence", "plot_collaboration_network",
    "plot_convergence", "plot_function",
    "plot_function_1d", "plot_function_2d", "plot_function_3d",
    "plot_function_contour", "plot_function_nd", "plot_function_surface",
    "plot_island_dynamics", "plot_population_snapshot",
    "AVAILABLE_CHAOTIC_MAPS", "AVAILABLE_TRANSFER_FUNCTIONS",
    "AVAILABLE_INIT_STRATEGIES", "AVAILABLE_REPAIR_STRATEGIES",
    "BinaryVar", "CategoricalVar", "FloatVar", "IntegerVar", "PermutationVar",
    "build_problem_spec", "decode_position", "encode_position", "utils",
    "ChaoticMap", "chaotic_population", "chaotic_sequence",
    "BinaryAdapter", "apply_transfer", "binarize",
    "vstf_01", "vstf_02", "vstf_03", "vstf_04",
    "sstf_01", "sstf_02", "sstf_03", "sstf_04",
    "HyperparameterTuner", "BenchmarkRunner", "tuner",
    "Problem", "FunctionalProblem", "ConstrainedFunctionalProblem",
    "SphereProblem", "RastriginProblem",
    "AckleyProblem", "RosenbrockProblem", "ZakharovProblem", "full_array",
    "get_init_function", "uniform_population", "lhs_population", "obl_population",
    "sobol_population", "chaotic_init_function",
    "get_repair_function", "limit", "limit_inverse", "rand", "reflect", "wang",
    "levy_flight",
    "list_test_problems", "list_engineering_problems",
    "get_engineering_problem", "get_engineering_problem_spec",
    "io", "load_checkpoint", "load_result",
    "result_from_json", "result_to_json",
    "save_checkpoint", "save_result",
]
